### PR TITLE
mod: update github.com/ajeddeloh/go-json to github.com/coreos/go-json

### PR DESCRIPTION
**Pull request by embik**
# Update `github.com/ajeddeloh/go-json` to `github.com/coreos/go-json`

The Github repository for github.com/ajeddeloh/go-json has moved to github.com/coreos/go-json. In addition, the pulled in version was quite old, so this commit updates the location and pulls in a newer version.

## How to use

Nothing special to be done as this is only a dependency update.

## Testing done

[Describe the testing you have done before submitting this PR. Please include both the commands you issued as well as the output you got.]

- [ ] Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update)
- [ ] Inspected CI output for image differences: `/boot` and `/usr` size, packages, list files for any missing binaries, kernel modules, config files, kernel modules, etc.

### CODE REVIEW

**Comment by pothos** [comment]
Hi, thank you for preparing this. Yet this repo is just kept for the Flatcar LTS 3033 release series and we don't really plan to do an Ignition update there (unless we have to due to, e.g., build problems). The development is done on https://github.com/coreos/ignition

**Comment by embik** [comment]
@pothos understood, thanks for the clarification. As a follow up question, does https://github.com/flatcar/container-linux-config-transpiler have the same maintenance status (if you know / can share)? I've only ended up in this repo because I was tracing the `go-json` dependency from `github.com/flatcar/container-linux-config-transpiler` here.

**Comment by pothos** [comment]
The `ct` config transpiler is still maintained but on low priority because we started to convert the docs to use [`butane`](https://github.com/coreos/butane) as replacement. Butane generates Ignition v3 and has some other cleanups and new features.

**Comment by embik** [comment]
Thanks, appreciate the additional information! I'll take a look at whether butane can be a replacement for us. I'll go ahead and close this PR.

**Pull request closed without merging**
