### PR TITLE
providers/ec2: refactor user data retrieval

### PR DESCRIPTION
**Pull request by hakman**
# Add support for IMDSv2
Updates aws-sdk-go to latest version to add support IMDSv2.
Refactors user data retrieval to use aws-sdk-go api.
Alternative to https://github.com/flatcar-linux/ignition/pull/19.

## How to use
Start a Flacar instance in AWS with IMDSv2 enabled. At the moment the instance fails to boot.
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-options.html

## Testing done
NONE

### CODE REVIEW

**Comment by pothos** [comment]
Thanks, @tormath1 is working on a Ignition v3 update - would this bring IMDSv2 from upstream Ignition?

**Comment by tormath1** [comment]
Thanks for this contribution - IMDSv2 is implemented in the upstream: https://github.com/coreos/ignition/commit/585c029f36cf7a027f22704759bb3c6600709b2d.

In the meantime, we could try to cherry-pick this commit to `flatcar-linux/ignition` ?

**Comment by hakman** [comment]
Thanks for checking this @tormath1 & @pothos. That upstream commit would be a good start.
Though I don't see the point of re-implementing the something that is part of `aws-sdk-go`, or maybe it does something extra that I am missing.
In any case, I don't mind if this PR is closed in favor of the cherry-pick.

**Comment by tormath1** [comment]
@hakman I personally agree on this statement:
> I don't see the point of re-implementing the something that is part of aws-sdk-go

IMHO, upstream was maybe not aware about this line:
```go
ec2metadata.New(f.AWSSession).GetUserData()
```

You could try to submit this PR to the upstream to get their review, then we will backport the upstream patch to this fork. The goal is to minimize the drift between this fork and the uptream in order to only have Flatcar related patches.

**Comment by hakman** [comment]
Thanks @tormath1. I agree. Could you take care of the cherry-pick of https://github.com/coreos/ignition/commit/585c029f36cf7a027f22704759bb3c6600709b2d?

**Comment by hakman** [comment]
Hopefully someone can address this in a better way soon.

**Comment by pothos** [comment]
The next Alpha release will introduce the new Ignition v3 support and also include the needed support, any improvements should go upstream.

**Comment by hakman** [comment]
Thanks for the update @pothos 👍

**Pull request closed without merging**
