### PR TITLE
platorm: support `gce` for compatiblity

### PR DESCRIPTION
**Pull request by tormath1**
we still have `OEM_ID=gce` so let's keep this "platform" as an alias of
`gcp`.

Signed-off-by: Mathieu Tortuyaux <mtortuyaux@microsoft.com>

### CODE REVIEW

**Comment by pothos** [comment]
We can do this change in bootengine as done for "aws" vs "ec2"

**Comment by pothos** [comment]
https://github.com/flatcar-linux/bootengine/blob/flatcar-master/dracut/30ignition/ignition-generator#L150
and https://github.com/flatcar-linux/init/blob/flatcar-master/systemd/system/oem-cloudinit.service#L8

**Comment by tormath1** [comment]
@pothos yes, let's do that ! I don't think we need to update this too: https://github.com/flatcar-linux/init/blob/flatcar-master/systemd/system/oem-cloudinit.service#L8 `cloudinit` still supports `gce` I guess.

**Comment by pothos** [comment]
> @pothos yes, let's do that ! I don't think we need to update this too: https://github.com/flatcar-linux/init/blob/flatcar-master/systemd/system/oem-cloudinit.service#L8 `cloudinit` still supports `gce` I guess.

I mean when the ignition result file talks about `gcp` we would have to add a case there to convert `gcp` to the cloudinit platform gce as done there with `aws` → `ec2-compat`.

**Pull request closed without merging**
