### PR TITLE
add backward compatibility

### PR DESCRIPTION
**Pull request by tormath1**
In this PR, we provide backward compatibility between v1, v2 and v3 of Ignition's config.

We use a forked `ign-converter` to ensure the conversion (https://github.com/flatcar-linux/ign-converter) - once the config loaded, `ignition` will check the version:

- `3.x`: it behaves as usual
- `2.x`: it tries to first parse with `v2_4` parser (which fallbacks to `1.x` if required) then it converts to `3.x`

high level changes:
- kept support for `oem://` file URLs, special handling of the OEM partition, CoreOS/Flatcar Container Linux config locations, translation of v1 and v2 configs to v3

## Testing done
- run kola tests (some tests support the 3 versions, like the `hostname` one)
- boot an instance with a custom Ignition (v1, v2 or v3) (use `systemd.journald.max_level_console=debug console=ttyS0` to get Ignition logs if it bootloops)

## Note for reviewers

- once merged, we can promote `main` to be the default branch and backup `flatcar-master` to `spec2x` to follow the upstream logic

### CODE REVIEW

**Comment by pothos** [comment]
`(info.format == fs.Format || info.label == "OEM")` would go here: https://github.com/kinvolk/ignition/blob/main/internal/exec/stages/disks/filesystems.go#L129 as port of https://github.com/kinvolk/ignition/commit/0a5340e560da1eb91b7d6266b9a46b358f8ebebf and https://github.com/kinvolk/ignition/commit/1c735118f7091f6b22d10945bf3b5fdf9e50dbee

and these two need to be ported: 4b3c0f9cce20be8083d8ca0e194051b1eba06117 3e27c2e58b3552dd580fecde59c3a15fcb7f4d07

Edit: the handling of ext4 OEM entries is now done in the translator instead of trying to mount all supported filesystems one by one

**Comment by pothos** [comment]
The ign-converter uses the files under `config/v1` and so on which are gone in this PR. We should either keep them around so that ign-converter can use this branch or we should "archive" the flatcar-master branch to have a place where we maintain the `config/v1` files etc.

Edit: Plan is to keep the current flatcar-master state around as `spec2` and take over the upstream branch names for our changes

**Review by pothos — APPROVED** [review]
I think we are good now with the kola tests passing?

**Comment by tormath1** [comment]
@pothos ok then - I started a new CI this morning using https://github.com/flatcar-linux/mantle/pull/301. If it's good, I'll go ahead and merge this one.
`ign-converter` dependency has been pinned to `v0.1.0` too.

**Pull request merged**
