### PR TITLE
Update AWS for IMDSv2

### PR DESCRIPTION
**Pull request by dustin-decker**
# Updates AWS dep to provide support for IMDSv2

https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/

Can I also move to go module like coreos/ignition has? Glide is not very good for updating deps.

# How to use

[ describe what reviewers need to do in order to validate this PR ]

# Testing done

None

### CODE REVIEW

**Comment by pothos** [comment]
Hello,

thanks for your PR here in addition to your upstream PR https://github.com/coreos/ignition/pull/980!

Sounds like this also needs to be done in Afterburn at the same time, or? If Ignition establishes a session, how would Afterburn gain access?

For Flatcar we need to update Ignition and Afterburn to follow upstream more closely. I'm not sure if we can include your changes and now already and drop them later before we rebase.

**Comment by dustin-decker** [comment]
Afterburn looks like it will be a bit more challenging. They wrote their AWS module in Rust, and I am not a Rust programmer. I will take a look though, the changes aren't large.

**Comment by pothos** [comment]
Reading the announcement it seems v1 and v2 can be used at the same time but it's recommended to disable v1 to benefit from v2. At first I thought using v2 would already imply that v1 style is not working anymore because it doesn't have the authentication.

**Comment by dustin-decker** [comment]
Yes, by default, both v1 and v2 work. With the current state of Ignition, CoreOS/Flatcar fails to boot if the token is required (v2). This change is backwards compatible with v1 but allows to boot if v2 is required. The lib will try v2 and fall back to v1.

**Comment by bgilbert** [comment]
> If Ignition establishes a session, how would Afterburn gain access?

The [IMDSv2 announcement](https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/) says:

> There’s no limit on the number of requests within a single session, and there’s no limit on the number of IMDSv2 sessions.

So I assume Afterburn can just create its own session.

**Comment by dustin-decker** [comment]
Support merged upstream in both ignition and afterburn: 

https://github.com/coreos/ignition/pull/980
https://github.com/coreos/afterburn/pull/426

**Comment by pothos** [comment]
All is done now, thanks everyone

**Pull request closed without merging**
