### PR TITLE
Merge upstream 2019-08-30

### PR DESCRIPTION
**Pull request by dongsupark**
_Please do not merge until it got reviewed, as this PR contains breaking changes_

This merge PR is mainly for avoiding merge conflicts.
However, it also ends up changing `cmdlineUrlFlag` from `flatcar.config.url` to `ignition.config.url`.
I'm still not sure if the change would work without any trouble.

### CODE REVIEW

**Comment by dongsupark** [comment]
Any chance for review?
It can be a breaking change.

**Comment by pothos** [comment]
`flatcar.config.url` is used in `mantle` at `platform/api/packet/api.go`, `init` at `tests/coreos-install/register/register.go`, in the PXE docs and the baremetal Lokomotive platform.

I'm in favor of using the generic `ignition.config.url`.

**Comment by dongsupark** [comment]
Summary of discussion with @pothos:
We should have a transition period for accepting both `flatcar.config.url` and `ignition.config.url`, to avoid breakage.

**Comment by dongsupark** [comment]
Superseded by https://github.com/flatcar-linux/ignition/pull/5.
Will close.

**Pull request closed without merging**
